development: &development
  # redis server host:port
  redis: localhost:6379
  # all cache keys will be prefixed with this
  cache_key_prefix: persues_shield
  # the bucket name to store the files in
  s3_bucket: my.bucket.s3
  # the root to use in the bucket
  s3_root:
  # AWS credentials
  aws_key: YOUR_KEY
  aws_secret: YOUR_SECRET
  # only urls that match this regex will be resized (no need for / at the start/end)
  url_regex: ^https?:\/\/.*\.?mywebsite\.com\/.+$
  # schemaless uri that points to the bucket's root 
  external_uri: cloudfront.mywebsite.com
test: &test
  <<: *development

production: &production
  redis: localhost:6379
  cache_key_prefix: persues_shield
  s3_bucket: my.bucket.s3
  s3_root:
  aws_key: YOUR_KEY
  aws_secret: YOUR_SECRET
  url_regex: ^https?:\/\/.*\.?mywebsite\.com.*$
  external_uri: cloudfront.mywebsite.com
